ALTER TABLE `owned_vehicles` ADD COLUMN IF NOT EXISTS `awrp_tuning` TEXT DEFAULT NULL;

INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('tuner_tablet', 'Tablet tunera', 1, 0, 1),
('tuner_repairkit', 'Zestaw naprawczy tunera', 1, 0, 1),
('tuner_enghoist', 'Podnośnik silnikowy tunera', 10, 0, 1),
('mod_engine', 'Silnik pojazdu', 50, 0, 1),
('mod_brakes', 'Hamulce pojazdu', 5, 0, 1),
('mod_transmission', 'Skrzynia biegów pojazdu', 25, 0, 1),
('mod_suspension', 'Zawieszenie pojazdu', 15, 0, 1),
('mod_armor', 'Opancerzenie pojazdu', 40, 0, 1),
('mod_turbo', 'Turbosprężarka pojazdu', 8, 0, 1),
('mod_exhaust', 'Układ wydechowy pojazdu', 10, 0, 1),
('mod_extras', 'Dodatki pojazdu', 2, 0, 1),
('mod_exterior', 'Zewnętrzne części pojazdu', 10, 0, 1),
('mod_interior', 'Wewnętrzne części pojazdu', 5, 0, 1),
('mod_fender', 'Błotnik pojazdu', 5, 0, 1),
('mod_frame', 'Podwozie pojazdu', 30, 0, 1),
('mod_frontbumper', 'Przedni zderzak pojazdu', 8, 0, 1),
('mod_grille', 'Kratka pojazdu', 3, 0, 1),
('mod_hood', 'Maska pojazdu', 10, 0, 1),
('mod_horn', 'Klakson pojazdu', 1, 0, 1),
('mod_light', 'Oświetlenie pojazdu', 2, 0, 1),
('mod_livery', 'Oklenie pojazdu', 1, 0, 1),
('mod_neon', 'Neony pojazdu', 2, 0, 1),
('mod_plate', 'Tablica rejestracyjna pojazdu', 1, 0, 1),
('mod_rearbumper', 'Tylny zderzak pojazdu', 8, 0, 1),
('mod_respray', 'Lakierowanie pojazdu', 2, 0, 1),
('mod_rim', 'Felga pojazdu', 5, 0, 1),
('mod_roof', 'Dach pojazdu', 10, 0, 1),
('mod_sideskirt', 'Próg pojazdu', 5, 0, 1),
('mod_spoiler', 'Spoiler pojazdu', 5, 0, 1),
('mod_tyresmoke', 'Dym z opon pojazdu', 1, 0, 1),
('mod_windowtint', 'Przyciemnianie szyb pojazdu', 1, 0, 1),
('mod_bullettires', 'Opony kuloodporne', 10, 0, 1),
('mod_drifttires', 'Opony do driftu', 10, 0, 1),
('mod_stocktires', 'Opony standardowe', 10, 0, 1),
('engine_v6', 'Silnik V6 Tuned', 60, 0, 1),
('engine_v8', 'Silnik V8 Supercharged', 80, 0, 1),
('engine_v12', 'Silnik V12 Hyper', 100, 0, 1)
ON DUPLICATE KEY UPDATE label = VALUES(label), weight = VALUES(weight);