-- Dodanie kolumny do tabeli pojazdów dla customowego tuningu
ALTER TABLE `owned_vehicles` ADD COLUMN IF NOT EXISTS `awrp_tuning` LONGTEXT DEFAULT NULL;

INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('tuner_tablet', 'Tablet tunera', 1, 0, 1),
('tuner_repairkit', 'Zestaw naprawczy tunera', 1, 0, 1),
('tuner_enghoist', 'Podnośnik silnikowy tunera', 1, 0, 1),
('mod_engine', 'Silnik pojazdu', 1, 0, 1),
('mod_brakes', 'Hamulce pojazdu', 1, 0, 1),
('mod_transmission', 'Skrzynia biegów pojazdu', 1, 0, 1),
('mod_suspension', 'Zawieszenie pojazdu', 1, 0, 1),
('mod_armor', 'Opancerzenie pojazdu', 1, 0, 1),
('mod_turbo', 'Turbosprężarka pojazdu', 1, 0, 1),
('mod_exhaust', 'Układ wydechowy pojazdu', 1, 0, 1),
('mod_extras', 'Dodatki pojazdu', 1, 0, 1),
('mod_exterior', 'Zewnętrzne części pojazdu', 1, 0, 1),
('mod_interior', 'Wewnętrzne części pojazdu', 1, 0, 1),
('mod_fender', 'Błotnik pojazdu', 1, 0, 1),
('mod_frame', 'Podwozie pojazdu', 1, 0, 1),
('mod_frontbumper', 'Przedni zderzak pojazdu', 1, 0, 1),
('mod_grille', 'Kratka pojazdu', 1, 0, 1),
('mod_hood', 'Maska pojazdu', 1, 0, 1),
('mod_horn', 'Klakson pojazdu', 1, 0, 1),
('mod_light', 'Oświetlenie pojazdu', 1, 0, 1),
('mod_livery', 'Oklenie pojazdu', 1, 0, 1),
('mod_neon', 'Neony pojazdu', 1, 0, 1),
('mod_plate', 'Tablica rejestracyjna pojazdu', 1, 0, 1),
('mod_rearbumper', 'Tylny zderzak pojazdu', 1, 0, 1),
('mod_respray', 'Lakierowanie pojazdu', 1, 0, 1),
('mod_rim', 'Felga pojazdu', 1, 0, 1),
('mod_roof', 'Dach pojazdu', 1, 0, 1),
('mod_sideskirt', 'Próg pojazdu', 1, 0, 1),
('mod_spoiler', 'Spoiler pojazdu', 1, 0, 1),
('mod_tyresmoke', 'Dym z opon pojazdu', 1, 0, 1),
('mod_windowtint', 'Przyciemnianie szyb pojazdu', 1, 0, 1),
('mod_bullettires', 'Opony kuloodporne', 1, 0, 1),
('mod_drifttires', 'Opony do driftu', 1, 0, 1),
('mod_stocktires', 'Opony standardowe', 1, 0, 1),
-- Poniżej przedmioty do Engine Swapów, które omówiliśmy wcześniej
('engine_v6', 'Silnik V6 Tuned', 1, 0, 1),
('engine_v8', 'Silnik V8 Supercharged', 1, 0, 1),
('engine_v12', 'Silnik V12 Hyper', 1, 0, 1);